alias lla='ls -la'
alias lt='ls --human-readable --size -1 -S --classify'
alias gh='history|grep'
alias cls='clear'
alias upd='sudo apt-get update -y && sudo apt-get upgrade -y'
alias gs='git status'
alias ga='git add .'
alias gp='git push'
alias gc=~/gc.sh
alias gl='git log'
alias cn='sudo mount.cifs //tiger/virtual ~/share -o user=alanr'
alias dc='docker'
alias dcu='docker compose up'
alias dcd='docker compose down'
